# Generated by Django 4.2.28 on 2026-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Nom de l’enseigne')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nom du contact')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail professionnel')),
                ('website', models.URLField(blank=True, verbose_name='Site internet')),
                ('address', models.TextField(verbose_name='Adresse de la boutique')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('invoiced', 'Facturé'), ('published', 'Publié'), ('rejected', 'Refusé')], db_index=True, default='new', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande de référencement',
                'verbose_name_plural': 'Demandes de référencement',
                'ordering': ['-created_at'],
            },
        ),
    ]
